### ISSUE TITLE
Script freezes when pressing arrow keys

### ISSUE THREAD

**Issue by martinber** [livibetter/pipes.sh#12]
When I press an arrow key the script should quit but instead if freezes, then I have to close it with Ctrl-C, when I press for example the A key the script closes correctly. It also freezes when pressing some strange key combination like Ctrl-Alt-A
I don't know bash scripting, but I started to comment lines until I found that the command that was stopping the script was in the cleanup() function. When I comment `cat </dev/stdin>/dev/null` pipes.sh closes correctly when pressing arrow keys
What is the purpose of `cat </dev/stdin>/dev/null`? 
Sorry for my english

**Comment by livibetter** [comment]
The `cat` "clear[s] up standard input before exits," see 10a7a5c17536e99d9b9d3a1298b04cd6dfa03528.

I am thinking this could be with #11, going back to old way to handle loop and inputs, might help or not. However, I am not in the mood to touch `pipes.sh`, so if anyone wants to give these two a try, please do.

**Comment by livibetter** [comment]
@martinber could you check to see if b267c7a fix the issue for you?

**Comment by martinber** [comment]
76fffba works OK for me, thanks!
